version: 0.2

artifacts:
  files:
    - '**/*'
  discard-paths: no

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 364021107285.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t connpass-frontend .
      - docker tag connpass-frontend:latest 364021107285.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-frontend:latest
      - printf '[{"name":"react-js","imageUri":"364021107285.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-frontend:latest"}]' > imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 364021107285.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-frontend:latest
